# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('work', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=250)),
                ('rating', models.CharField(choices=[('1', 'One star'), ('2', 'Two stars'), ('3', 'Three stars'), ('4', 'Four stars'), ('5', 'Five stars')], max_length=16)),
                ('website', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, default='', max_length=10)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hotel')),
            ],
        ),
    ]
